<Time>:

<Temperature>:

<Wallpaper>:
    source: './wallpapers/01947_atouchofred_1920x1080.jpg'
    size_hint: 1, 1

<Label>:
    size_hint: None, None
    font_name: './fonts/Roboto-Regular.ttf'
    font_size: 50

<FloatLayout>:

	Wallpaper:
        id: wallpaper
	    pos_hint: {'center_x': .5, 'center_y': .5}

    Time:
        id: time
		pos_hint: {'right': 0.2, 'top': 0.99}

    Temperature:
        id: temperature
		pos_hint: {'right': 0.89, 'top': 0.99}
        text: "Temperature: 26°C"